### ISSUE TITLE
Issue with Tapas package installation 

### ISSUE THREAD

**Issue by matiuadex** [wfinsinger/tapas#5]
Hello,

I am trying to use tapas for the first time but the package isn't installing using the code line on the page. I was wondering if there is a new one. Please help. See code below in including error received. 

> devtools::install_github("wfinsinger/tapas")
Downloading GitHub repo wfinsinger/tapas@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/wfinsinger/tapas/tarball/HEAD'

**Comment by wfinsinger** [comment]
Hi Matiudex,

Many thanks for your message.

Mmmhhh, maybe you could try fetching the package using the 'remotes' package rather than 'devtools'.
Could you try with the following command line and let me know if it worked?
remotes::install_github("wfinsinger/tapas", force = TRUE, dependencies = TRUE,
                        build_vignettes = TRUE)

On my Mac (macOS version 10.15.7) with R version 4.2.2 and RStudio Version 2022.12.0+353 (2022.12.0+353) both devtools (version 2.4.5) and remotes (version 2.4.2) work well.

Cheers,

Walter

**Comment by matiuadex** [comment]
Hello Walter,

Apologies for my delayed response. Thank you for your suggestion, it worked! Really appreciate.

Regards,
Matthew.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wfinsinger** [comment]
Hi Matthew,

Many thanks for your message. Great!
Ciao ciao,
Walter
